apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wastewater-epi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Informatics-bphc/wastewater-gitops.git
    targetRevision: main
    path: wastewater-epi
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
