---
output: 
  html_document:
    theme:
      primary: "#072671"
      bootswatch: "litera"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
library("here")
library("bslib")
library(shiny)
library(htmltools)
library(plotly)
library(leaflet)
```

```{r}
plotly_widget <- plot_ly(x = diamonds$cut) %>%
  config(displayModeBar = FALSE) %>%
  layout(margin = list(t = 0, b = 0, l = 0, r = 0))

leaflet_widget <- leafletOptions(attributionControl = FALSE) %>%
  leaflet(options = .) %>%
  addTiles()

# Import Map
map_loc <- "/DataDrive/covid19/wastewater/wastewater-epi/_outputs/HTML/leaf_map.rds"
covid_map <- readRDS(map_loc)

html_map_loc <- "/DataDrive/covid19/wastewater/wastewater-epi/_outputs/HTML/leaf_map.html"
#file.copy(from = html_map_loc, to = here::here("docs", "leaf_map.html"), overwrite = TRUE)
```

```{r}
sparkline <- plot_ly(economics) %>%
  add_lines(
    x = ~date, y = ~psavert,
    color = I("white"), span = I(1),
    fill = 'tozeroy', alpha = 0.2
  ) %>%
  layout(
    xaxis = list(visible = F, showgrid = F, title = ""),
    yaxis = list(visible = F, showgrid = F, title = ""),
    hovermode = "x",
    margin = list(t = 0, r = 0, l = 0, b = 0),
    font = list(color = "white"),
    paper_bgcolor = "transparent",
    plot_bgcolor = "transparent"
  ) %>%
  config(displayModeBar = F) %>%
  htmlwidgets::onRender(
    "function(el) {
      var ro = new ResizeObserver(function() {
         var visible = el.offsetHeight > 200;
         Plotly.relayout(el, {'xaxis.visible': visible});
      });
      ro.observe(el);
    }"
  )


vb_sparkline <- value_box(
  title = "Covid-19 Trends",
  value = "7.6%",
  p("Started at 12.6%"),
  p("Averaged 8.6% over that period"),
  showcase = sparkline,
  full_screen = TRUE,
  theme = "primary"
)

vb2 <- value_box(
  title = "Energy consumption",
  value = "345 kwh/month",
  showcase = bsicons::bs_icon("ev-station-fill")
)

vb3 <- value_box(
  title = "Test Title",
  value = "-56%",
  showcase = bsicons::bs_icon("arrow-down-right")
)
```

```{r}
# NH Card w/ Info
navset_card_tab(
  height = 600,
  full_screen = TRUE,
  title = "NH Levels & Trends",
  nav_panel(bsicons::bs_icon("map"), covid_map),
  nav_panel(bsicons::bs_icon("table"), "Table"),
  nav_panel(
    shiny::icon("circle-info"),
    markdown("Learn more about [BPHC's wastwater program](https://www.boston.gov/government/cabinets/boston-public-health-commission/boston-wastewater-monitoring)")
  ),
  card_footer(
    class = "fs-6",
    "Data Through "
  )
)

```

# RSV & Flu Tabs

```{r}
navset_card_tab(
  height = 600,
  full_screen = TRUE,
  title = "Latest Wastewater",
  nav_panel(
    "COVID-19",
    layout_column_wrap(
      #width = 1/2,
      style = css(grid_template_columns = "1fr 2fr"),
    #  height = 300,
      list(vb_sparkline, vb2, vb3),
      card(full_screen = TRUE, card_header("NH Levels & trends"), card_body(class = "p-0", covid_map))
    )
  ),
  nav_panel(
    "RSV",
    card_title("A plotly plot"),
    plotly_widget
  ),
  nav_panel(
    "Influenza",
    card_title("A leaflet plot"),
    leaflet_widget
  ),
  

  nav_panel(
    shiny::icon("circle-info"),
    markdown("Learn more about [BPHC's wastwater program](https://www.boston.gov/government/cabinets/boston-public-health-commission/boston-wastewater-monitoring)")
  ),
  card_footer(
    class = "fs-6",
    "Data Through "
  )
)
```



```{r}
card(
  card_header(
    class = "bg-light",
    "A header"
  ),
  card_body(
    markdown("Some text with a [link](https://tori-cowger.github.io/wastewater_web/)")
  )
)
```

```{r}
card(
  height = 275,
  full_screen = TRUE,
  card_header("A filling map"),
  card_body(
    class = "p-0",
    leaflet_widget
  ),
  card_footer(
    class = "fs-6",
    "Copyright 2023 RStudio, PBC"
  )
)
```

```{r}
layout_column_wrap(
  width = 1/2,
  height = 300,
  card(full_screen = TRUE, card_header("A filling plot"), plotly_widget),
  card(full_screen = TRUE, card_header("A filling map"), card_body(class = "p-0", leaflet_widget))
)
```

```{r}
navset_card_tab(
  height = 450,
  full_screen = TRUE,
  title = "HTML Widgets",
  nav_panel(
    "Plotly",
    card_title("A plotly plot"),
    plotly_widget
  ),
  nav_panel(
    "Leaflet",
    card_title("A leaflet plot"),
    leaflet_widget
  ),
  nav_panel(
    shiny::icon("circle-info"),
    markdown("Learn more about [htmlwidgets](http://www.htmlwidgets.org/)")
  )
)
```

# Info Button Options
```{r}
card_add_info_tab <- function(main_header, main_content, info_content, full_screen = FALSE, height = NULL){
  tab_out <- navset_card_pill(full_screen = full_screen, 
                             height = height,
                  nav_panel(main_header, main_content), 
                  nav_panel(shiny::icon("circle-info"), info_content))
  return(tab_out)
}

card_add_info_popover <- function(main_header, main_content, info_header = NULL, info_content, full_screen = FALSE, height = NULL, 
                                  header_class = "bg-light"){
  pop_info <- popover(shiny::icon("circle-info"), title = info_header, info_content)
  tab_out <- card(full_screen = full_screen, 
                             height = height,
                  card_header(main_header, pop_info, class = paste("d-flex justify-content-between", header_class)),
                  card_body(main_content))
  return(tab_out)
}


card_add_info_tab(h5(strong("Boston Citywide Levels & Trends")), vb_sparkline2, p("Info Text"), height= 500)
card_add_info_popover(h5(strong("Boston Citywide Levels & Trends")), main_content = vb_sparkline2, 
                      info_header = "Info Header", info_content = p("Info Text"), height= 500)


accordian_test <- accordion(
  accordion_panel(icon = shiny::icon("circle-info"), 
                  title = "Info",
                  p("Accordian info", class = "text-secondary")
                  ), 
  open = FALSE
  )

accordian_test2 <- accordion(
  accordion_panel(icon = shiny::icon("circle-info"), 
                  title = "Info",
                  p("Standalone accordian", class = "text-secondary")
                  ), 
  open = FALSE
  )

card(
  card_header("Header", class = "bg-danger"),
  vb_icon,
  card_footer(accordian_test),
  
  )

accordian_test2
```



```{r}


card_image_pre <- card(
  #height = 300,
  
  full_screen = FALSE,
  card_header("HEADER", class = "bg-light"),
  card_image(height = circle_size, width = circle_size,
    file = here("docs","img", "circ_high_stable.png"),
    class = "img-center"
  ),
  card_body(
    fill = FALSE,
    value_box("Title", value="High", p("text2")), 
    value_box("Title", value="High", p("text2")), 
    #card_title("Shiny for R"),
    p(
      class = "fw-success text-muted",
      "Brought to you by RStudio."
    )
  )
)

card_image_pre2 <- card(
  
  layout_column_wrap(
  style = css(grid_template_columns = "1fr 2fr"),
  img(src = here("docs","img", "circ_high_stable.png"), height = "200", width = "200"),
  list(value_box("Title", value="High", p("text2")), 
  value_box("Title", value="High", p("text2")))
)
  
)
card_image_pre
```

```{r}
link_shiny <- tags$a(shiny::icon("github"), "Shiny", href = "https://github.com/rstudio/shiny", target = "_blank")
link_posit <- tags$a(shiny::icon("r-project"), "Posit", href = "https://posit.co", target = "_blank")

page_navbar(
  title = "My App",
 # bg = "#0062cc",
  underline = TRUE,
  nav_panel(title = "One", p("First tab content.")),
  nav_panel(title = "Two", p("Second tab content.")),
  nav_panel(title = "Three", p("Third tab content")),
  nav_spacer(),
  nav_menu(
    title = "Links",
    align = "right",
    nav_item(link_shiny),
    nav_item(link_posit)
  )
)
```

```{r eval=FALSE, include=FALSE}
source_folder <- here()
output_folder <- here("docs")
rmarkdown::render(input = paste0(source_folder, "/", "cards.Rmd"),
                  output_format = "html_document",
                  output_file = "cards.html",
                  output_dir = output_folder)
```
