apiVersion: apps/v1
kind: Deployment
metadata:
  name: wastewater-web
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wastewater-web
  template:
    metadata:
      labels:
        app: wastewater-web
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/index.html  # Explicitly replace index.html
          subPath: index.html  # Map only the index.html file from ConfigMap
          name: app-content
      volumes:
      - name: app-content
        configMap:
          name: wastewater-web-content
