apiVersion: v1
kind: Service
metadata:
  name: wastewater-web
  labels:
    app: wastewater-web
spec:
  selector:
    app: wastewater-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
