apiVersion: v1
kind: Service
metadata:
  name: wastewater-web
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: wastewater-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
