apiVersion: apps/v1
kind: Deployment
metadata:
  name: wastewater-epi
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wastewater-epi
  template:
    metadata:
      labels:
        app: wastewater-epi
    spec:  # Ensure this field is correctly placed here
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
