apiVersion: v1
kind: Service
metadata:
  name: wastewater-epi
  namespace: default
spec:
  selector:
    app: wastewater-epi
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
