apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wastewater-web  # Hyphen for ArgoCD compatibility
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Informatics-bphc/wastewater-gitops.git
    targetRevision: main
    path: wastewater_web/k8s  # Underscore to match GitHub repo structure
  destination:
    server: https://kubernetes.default.svc
    namespace: wastewater
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
