apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wastewater-epi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Informatics-bphc/wastewater-gitops.git
    targetRevision: main
    path: wastewater-epi/k8s  # Keep as is
  destination:
    server: https://kubernetes.default.svc
    namespace: wastewater
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wastewater_web  # Fix name to use underscore to match GitHub
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Informatics-bphc/wastewater-gitops.git
    targetRevision: main
    path: wastewater_web/k8s  # Match correct directory
  destination:
    server: https://kubernetes.default.svc
    namespace: wastewater
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
