name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: false

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: bphcdmiacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t bphcdmiacr.azurecr.io/wastewater-web:latest -f wastewater_web/Dockerfile wastewater_web
          docker push bphcdmiacr.azurecr.io/wastewater-web:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: false

      - name: Install Kubectl and Kubelogin
        run: |
          az aks install-cli
          sudo az aks install-kubelogin

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group DMI-Dev --name bphc-modernization-cluster

      - name: Deploy Application to AKS
        run: |
          kubelogin convert-kubeconfig -l azurecli
          kubectl apply -f wastewater_web/deployment.yaml
          kubectl apply -f wastewater_web/service.yaml
          kubectl rollout status deployment/wastewater-web -n default
